### PR TITLE
Unicode 6.3.0 update

### PR DESCRIPTION
**Pull request by skull-squadron**
Like it says on the tin.

### CODE REVIEW

**Comment by pjg** [comment]
Could we get this merged and released? :)

**Comment by grosser** [comment]
@lang ?

**Comment by skull-squadron** [comment]
Unicode 7 was released.  This needs to be updated by someone that has the bandwidth.  Feel free to close this and steal liberally.

—

**Comment by matkoniecz** [comment]
> Could we get this merged and released? :)

Given that last update of this repo was in 2012 it is not likely. Is there a viable drop-in replacement for this library?

**Comment by grosser** [comment]
@lang help ? :D

**Comment by skull-squadron** [comment]
@grosser Waiting for @lang is waiting for Godot. ;) 0 activity since 2012. Either has kids, became a monk or went into management. :)

Maybe someone whom uses this oughta fork this as `unicode_utils2`, `unicode_utils_next`, etc. or contrib to another package that provides similar functionality.

**Pull request closed without merging**
